"use client"

import Link from "next/link"
import Image from "next/image"
import "./globals.css"
import { Inter } from "next/font/google"
import { Analytics } from "@/components/analytics"
import { useMediaQuery } from "react-responsive"
import { useState, useEffect } from "react"
const inter = Inter({ subsets: ["latin"] })

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  const isDesktop = useMediaQuery({ maxWidth: "768px" })
  const [scrollPos, setScrollPos] = useState(0)
  const [isSticky, setSticky] = useState(true)

  useEffect(() => {
    const handleScroll = () => {
      const currentScrollPos = window.scrollY

      // Check if scrolling down and not at the top
      if (currentScrollPos > scrollPos && currentScrollPos > 0) {
        setSticky(false)
      } else {
        setSticky(true)
      }

      setScrollPos(currentScrollPos)
    }

    window.addEventListener("scroll", handleScroll)

    return () => {
      window.removeEventListener("scroll", handleScroll)
    }
  }, [scrollPos])

  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-white text-slate-900 ${inter.className}`}
      >
        <header>
          <nav
            className={`flex bg-white items-center justify-between px-6 py-4 md:px-12 ${
              isSticky ? "fixed top-0 w-full" : "relative"
            }`}
          >
            <Link href="/">
              <Image src="/logo.svg" width={120} height={120} alt="Your Logo" />
            </Link>
            {!isDesktop ? (
              <div className="flex justify-center align-items space-x-12">
                <div className="flex font-semibold justify-center items-center text-xl space-x-6">
                  <Link href="/stories">Stories</Link>
                  <Link href="/justice">Justice</Link>
                  <Link href="/fund">Fund</Link>
                </div>
                <Link href="/donate">
                  <button className="px-4 py-2 mt-1 rounded-md bg-red-500 text-white font-bold hover:bg-red-600">
                    Donate
                  </button>
                </Link>
              </div>
            ) : (
              <div className="flex justify-center align-items space-x-4">
                <Link href="/donate">
                  <button className="px-4 py-2 mt-1 rounded-md bg-red-500 text-white font-bold hover:bg-red-600">
                    Donate
                  </button>
                </Link>
                <button className="">
                  <Image
                    src="/burger.svg"
                    width={40}
                    height={40}
                    alt="Dropdown Icon"
                  />
                </button>
              </div>
            )}
          </nav>
        </header>
        <div className="max-w-full min-h-screen bg-skin">
          <main>{children}</main>
        </div>
        <Analytics />
      </body>
    </html>
  )
}
